from langgraph.graph import StateGraph, START, END

from .graph_state import GraphState
from .ingestion_helper import get_vector_store
from rag.embeddings import embed_text
from app.config import settings
from .code_qa_chain import answer_with_context
from .ingestion_helper import get_vector_store, init_or_refresh_vector_store



def planner_node(state: GraphState) -> GraphState:
    """
    Very simple 'planner' for now.

    It only classifies the message type.
    Later it can decide which agent to call (code_qa, docs, etc.).
    """
    user_input = state.get("user_input", "")
    msg_type = "question" if user_input.strip().endswith("?") else "statement"
    return {"message_type": msg_type}



def ingestion_node(state: GraphState) -> GraphState:
    """
    Ingestion node (Phase: local demo).

    - Ensures the in-memory vector store is initialized/refreshed
      from the local 'sample_data' folder.
    - Does not change the reply; it only prepares data for RAG.
    """
    # This will read from sample_data/ and rebuild the store
    init_or_refresh_vector_store()

    # You could track ingestion metadata in state later (e.g., timestamps)
    return state



def code_qa_node(state: GraphState) -> GraphState:
    """
    Code-QA node using RAG, with optional LLM.

    - Always:
      - Embeds the user_input using local embeddings.
      - Searches the in-memory vector store.
    - If settings.use_llm is True:
      - Calls LLM with retrieved chunks as context to generate an answer.
    - Otherwise:
      - Returns a RAG-only answer composed from the retrieved snippets.
    """
    user_input = state.get("user_input", "")
    if not user_input:
        return {"reply": "I did not receive any input.", "retrieved_chunks": []}

    # 1) RAG retrieval (always)
    store = get_vector_store()
    query_emb = embed_text(user_input)
    top_chunks = store.search(query_emb, top_k=3)
    retrieved_texts = [c.text for c in top_chunks]

    # 2) If LLM disabled, return RAG-only answer
    if not settings.use_llm or not settings.openai_api_key:
        joined_snippets = " | ".join(retrieved_texts) if retrieved_texts else "No relevant text found."
        reply = (
            f"[RAG only] You asked: '{user_input}'. "
            f"Top snippets from knowledge base: {joined_snippets}"
        )
        return {
            "retrieved_chunks": retrieved_texts,
            "reply": reply,
        }

    # 3) LLM-enabled path
    try:
        llm_answer = answer_with_context(user_input, retrieved_texts)
        return {
            "retrieved_chunks": retrieved_texts,
            "reply": llm_answer,
        }
    except Exception as e:
        # Fallback if LLM fails
        fallback = (
            f"[RAG fallback] Retrieved {len(retrieved_texts)} snippet(s) "
            f"but LLM call failed: {e}"
        )
        return {
            "retrieved_chunks": retrieved_texts,
            "reply": fallback,
        }



def build_graph():
    """
    Build and compile a LangGraph graph:

    START -> planner_node -> code_qa_node -> END
    """
    builder = StateGraph(GraphState)

    builder.add_node("planner_node", planner_node)
    builder.add_node("ingestion_node", ingestion_node)
    builder.add_node("code_qa_node", code_qa_node)

    # Simple flow for now: always ingest, then QA
    builder.add_edge(START, "planner_node")
    builder.add_edge("planner_node", "ingestion_node")
    builder.add_edge("ingestion_node", "code_qa_node")
    builder.add_edge("code_qa_node", END)


    graph = builder.compile()
    return graph


graph_app = build_graph()




# Planner still sets message_type (we’ll use it later).
# code_qa_node uses the “fake RAG” components to retrieve snippets and build a reply.

# Now:
# Ingestion uses embed_chunks → real sentence‑transformers embeddings.
# Query uses embed_text → real embeddings.
# Similarity search is still naive but now based on a meaningful vector space.

#Now:
# Retrieval still uses your local vector store + sentence‑transformers.
# Final reply is generated by the LLM, given the retrieved context.

# Now we have truly have both:
# When USE_LLM=false or OPENAI_API_KEY is empty:
# RAG‑only mode, fully local.
# When USE_LLM=true and a valid key is set:
# RAG + online LLM answers.


# So the graph path is now:
# START → planner_node → ingestion_node → code_qa_node → END.

# This means:
# Every request:
# Planner runs (still just classifies).
# Ingestion ensures vector store is built from sample_data.
# Code‑QA uses that store to answer.

# Later, planner will decide whether ingestion is needed or not.


